AS_ARM = arm-none-eabi-as
LD_ARM = arm-none-eabi-ld
CFLAGS = -march=armv2a -mno-thumb-interwork -Wall -O1
LD_FLAGS = -Bstatic -fix-v4bx

all : test1

test1 : test1.o
	${LD_ARM} ${LD_FLAGS} -T sections.lds -o test1 test1.o

test1.o : test1.s
	${AS_ARM} -c test1.s -o test1.o

clean :
	rm -f test1 *.o
